version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: azzr/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  
  frontend:
    env_file: .env
    image: azzr/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    image: azzr/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
    - backend
    - frontend
